name: PyTest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  pytest:
    name: Run the application's tests with PyTest
    runs-on: ubuntu-20.04
    container: fedora:34
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run pytest -v
